version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgresql:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: octopus-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: octopus
    volumes:
      - mysql_data:/var/lib/mysql

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3004:3004"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres/octopus-postgres?schema=public
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    depends_on:
      - postgresql
      - rabbitmq

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "3003:3003"
    environment:
      MONGO_URI: mongodb://mongodb/octopus-product
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    depends_on:
      - mongodb
      - rabbitmq

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongodb/octopus-cart
    depends_on:
      - mongodb

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: mysql://root:mysecretpassword@mysql/octopus
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      CART_SERVICE: http://cart-service:3001
      PRODUCT_SERVICE: http://product-service:3003
    depends_on:
      - mysql
      - rabbitmq

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      CART_SERVICE: http://cart-service:3001
      ORDER_SERVICE: http://order-service:3002
      PRODUCT_SERVICE: http://product-service:3003
      USER_SERVICE: http://user-service:3004
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service

volumes:
  postgres_data:
  mongo_data:
  mysql_data:
